### ISSUE TITLE
Reddit share icon seems to be missing

### ISSUE THREAD

**Issue by NikoRoberts** [huacnlee/social-share-button#112]
Reddit is on by default but the icon doesn't seem to be displaying properly. It just appears as a red button

**Comment by huacnlee** [comment]
social-share-button used AVG format icon, you need make sure you Application user browser supported that!

https://github.com/huacnlee/social-share-button/blob/master/app/assets/images/social-share-button/reddit.svg

Please open this url, can you see the right Icon like this:

<img width="310" alt="2016-11-21 2 34 42" src="https://cloud.githubusercontent.com/assets/5518/20472847/aa21cb1a-aff7-11e6-9b39-d63fb375a626.png">

If not, tell me which Browser and version do you used?

**Comment by JeffLoo-ong** [comment]
I'm getting something similar while developing on Linux (Ubuntu LTS 16.04).

I am seeing a strange icon on Chromium 53.0.2785.143 and something else on Firefox 50.0

http://imgur.com/a/L5Sqr (Chromium image on top and Firefox image on bottom)

When I click the github link you provided to the image I saw this in the Google Dev Tools: 

Refused to load the script 'data:application/javascript;base64,KGZ1bmN0aW9uKCkgewoJLy8gaHR0cHM6Ly9kZXZl…07Cgl9OwoJZ2EucmVtb3ZlID0gbm9vcGZuOwoJd2luZG93W2dhTmFtZV0gPSBnYTsKfSkoKTs=' because it violates the following Content Security Policy directive: "script-src 'self' www.google-analytics.com".

Hope this helps to solve problem!

**Comment by NikoRoberts** [comment]
@JeffLoo-ong that's your secure headers blocking the use of all base64 images. That isn't my problem 

@huacnlee any browser I try. See any article on  https://www.eventfuel.io/blog

**Comment by AcceptableIce** [comment]
The icon is not displaying for me either.

**Comment by huacnlee** [comment]
close by https://github.com/huacnlee/social-share-button/pull/117
